#!/bin/bash -l

# Usage: worker identity action
# Eg: worker warehouse_two.production.1 start

function worker_start() {
  cd `pwd`
  if [ ! -f ../../shared/worker.${1}.pid ]
  then
    echo "Starting Amqp worker"
    nohup bundle exec ./script/amqp_loader main &
    echo $! > ../../shared/worker.${1}.pid
  else
    echo "Worker already running with pid:"
    echo `cat ../../shared/worker.${1}.pid`
  fi
}

function worker_stop() {
  cd `pwd`
  kill -9 `cat ../../shared/worker.${1}.pid`
  if [ -f ../../shared/worker.${1}.pid ]; then rm ../../shared/worker.${1}.pid; fi
}

function worker_restart() {
  worker_stop
  worker_start
}

worker_${2} $1
